name: Terraform deployment for alb
on: [push]
jobs:
  terraform-alb:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      # EXPORT THE CREDENTIALS - MARKETPLACE : "Configure AWS Credentials ACTION  GitHub Actions"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::029687280754:role/github-actions-oidc
          aws-region: "eu-central-1"

      - name: Clone/Checkout your repository code infra
        uses: actions/checkout@v2

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v1

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan